// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urhgboiqkvxlmrvlfets.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaGdib2lxa3Z4bG1ydmxmZXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzM4OTIsImV4cCI6MjA2OTc0OTg5Mn0.6epSIyWEWT7SaoLIZZZkQ2koo6FVQQ01OUuC7LEYgaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});